### PR TITLE
Copy the procfetch.gif

### PR DESCRIPTION
**Pull request by youpong**
## Description

Fix  Issue #95

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
Are you sure this will fix it?
It will only fix when generating docs locally.
[Here](https://github.com/TanmayPatil105/doxygen-github-pages-action/blob/main/action.yml) we are running doxygen and not `make docs`!

**Comment by youpong** [comment]
As you point out, this fix is limited to improvements only when you are generating documents locally.

**Comment by TanmayPatil105** [comment]
Should I can make changes [here](https://github.com/TanmayPatil105/doxygen-github-pages-action/blob/main/action.yml) inorder to fix it?

```
    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y
      shell: bash

    - name: Configure
      run: ./configure
      shell: bash

    - name: Generate Doxygen Documentation
      run: make docs
      shell: bash

```

**Comment by youpong** [comment]
I think that fix would help to fix it.

**Comment by TanmayPatil105** [comment]
It is still not fixed ig!

**Comment by TanmayPatil105** [comment]
Let me try different Workflows to see how we can fix it.

**Comment by TanmayPatil105** [comment]
My bad, I didn't release the updated version! LOL

**Comment by TanmayPatil105** [comment]
Fixed 🔧!

**Pull request merged**
