### PR TITLE
Introduce class Context

### PR DESCRIPTION
**Pull request by youpong**
## Description

Introduce class Context which contains PACKAGE_DELIM.

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
Looks good!
Anyway to increase the coverage?

**Comment by youpong** [comment]
I think the coverage test cannot be increased as far as the modifications in this Pull Request.

**Comment by TanmayPatil105** [comment]
LGTM!

**Comment by youpong** [comment]
So we adopt this PR and discard #97, is that correct?

**Comment by TanmayPatil105** [comment]
Yupp

**Pull request merged**
