### PR TITLE
Introduce asynchronous Command::exec_async() 

### PR DESCRIPTION
**Pull request by youpong**
Get package info in concurrency.

20% shorter processing time in my env.

## Related Discussion(s)
* #92

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
Will have a look at it 👍🏻

**Comment by TanmayPatil105** [comment]
LGTM 
- for `procfetch`
```
procfetch  1.11s user 0.44s system 70% cpu 2.196 total
```
- for `./src/procfetch`
```
./src/procfetch  1.32s user 0.31s system 100% cpu 1.614 total
```

**Comment by youpong** [comment]
It wasn't a dramatic improvement that cut the response time in half.
I think the I/O is critical even if multiple processes are run in parallel.

**Comment by TanmayPatil105** [comment]
Yupp very interesting!
Ready to merge?

**Pull request merged**
