### PR TITLE
Update fetch.cpp

### PR DESCRIPTION
**Pull request by youpong**
1. Make it simple: l. 448 - l.452
2. Multiply and then let floating point do the math: l.470
3. Let the emoji remain unchanged: l.472

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
So, I should merge PR #115 and then #116  right?

**Comment by youpong** [comment]
Yup

**Comment by TanmayPatil105** [comment]
Dkw why but changes are not reflected!

**Comment by TanmayPatil105** [comment]
Ohh f this PR was for branch `feat-battery` and not `main`

**Comment by TanmayPatil105** [comment]
Done!

**Pull request merged**
