### PR TITLE
🔒 Add flag for battery

### PR DESCRIPTION
**Pull request by TanmayPatil105**
## Changes proposed

-  `Battery` percentage is disabled by default
-  Add `-b` flag to display battery percentage
-  Added customisations to `README.md`

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
@youpong prefer proposing changes in this PR instead of creating a new PR :)

**Comment by TanmayPatil105** [comment]
@youpong prefer proposing changes in this PR instead of creating a new PR :)

**Comment by TanmayPatil105** [comment]
@youpong prefer proposing changes in this PR instead of creating a new PR :)

**Review by youpong — CHANGES_REQUESTED** [review]
Quote from `getopt(3)`:
> `optstring` is a string containing the legitimate option characters.  If such a character is followed by a colon, the option requires an argument, ...

So, Just `b` should be added to the `optstring` argument of `getopt(3)`. Now we are trying to add `:b`  preceded by a colon:

```diff
-     while ((opt = getopt(argc, argv, "ta:d:v:b")) != -1)
+     while ((opt = getopt(argc, argv, "ta:d:vb")) != -1)
```

**Comment by TanmayPatil105** [comment]
> So, Just `b` should be added to the `optstring` argument of `getopt(3)`. Now we are trying to add `:b` preceded by a colon:

Done

**Review by youpong — APPROVED** [review]

**Comment by TanmayPatil105** [comment]
Should I draft a new release or wait until we get all things correct related to `INSTALL_LIB_DIR` get right?
It didn't break the code. So, we can ig.

**Comment by youpong** [comment]
No need to wait.

**Pull request merged**
